export const ErrorCode = {
  // Common
  COMMON_SUCCESS: 'COMMON_SUCCESS',
  COMMON_BAD_REQUEST: 'COMMON_BAD_REQUEST',
  COMMON_UNAUTHORIZED: 'COMMON_UNAUTHORIZED',
  COMMON_FORBIDDEN: 'COMMON_FORBIDDEN',
  COMMON_NOT_FOUND: 'COMMON_NOT_FOUND',
  COMMON_CONFLICT: 'COMMON_CONFLICT',
  COMMON_UNPROCESSABLE_ENTITY: 'COMMON_UNPROCESSABLE_ENTITY',
  COMMON_RATE_LIMIT_EXCEEDED: 'COMMON_RATE_LIMIT_EXCEEDED',
  COMMON_INTERNAL_ERROR: 'COMMON_INTERNAL_ERROR',
  COMMON_SERVICE_UNAVAILABLE: 'COMMON_SERVICE_UNAVAILABLE',
  COMMON_UNKNOWN_ERROR: 'COMMON_UNKNOWN_ERROR',
  COMMON_NO_USER_CONTEXT: 'COMMON_NO_USER_CONTEXT',
  COMMON_RESOURCE_ID_NOT_FOUND: 'COMMON_RESOURCE_ID_NOT_FOUND',
  COMMON_USER_NOT_FOUND: 'COMMON_USER_NOT_FOUND',

  // Prisma
  COMMON_RESOURCE_ALREADY_EXISTS: 'COMMON_RESOURCE_ALREADY_EXISTS',
  COMMON_RESOURCE_NOT_FOUND: 'COMMON_RESOURCE_NOT_FOUND',
  COMMON_RELATED_RESOURCE_NOT_FOUND: 'COMMON_RELATED_RESOURCE_NOT_FOUND',
  COMMON_INVALID_INPUT: 'COMMON_INVALID_INPUT',
  COMMON_DATABASE_TIMEOUT: 'COMMON_DATABASE_TIMEOUT',

  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_DEACTIVATED: 'AUTH_ACCOUNT_DEACTIVATED',
  AUTH_TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_NOT_FOUND: 'AUTH_REFRESH_TOKEN_NOT_FOUND',
  AUTH_CURRENT_PASSWORD_INCORRECT: 'AUTH_CURRENT_PASSWORD_INCORRECT',
  AUTH_RESET_TOKEN_INVALID: 'AUTH_RESET_TOKEN_INVALID',

  // User
  USER_EMAIL_IN_USE: 'USER_EMAIL_IN_USE',
  USER_CANNOT_MANAGE_ADMIN_ROLE: 'USER_CANNOT_MANAGE_ADMIN_ROLE',
  USER_INVALID_ROLE_IDS: 'USER_INVALID_ROLE_IDS',

  // RBAC
  RBAC_ROLE_NOT_FOUND: 'RBAC_ROLE_NOT_FOUND',
  RBAC_CANNOT_DELETE_SYSTEM_ROLE: 'RBAC_CANNOT_DELETE_SYSTEM_ROLE',
  RBAC_CANNOT_DELETE_ROLE_WITH_USERS: 'RBAC_CANNOT_DELETE_ROLE_WITH_USERS',
  RBAC_INSUFFICIENT_PERMISSIONS: 'RBAC_INSUFFICIENT_PERMISSIONS',
  RBAC_OWN_RESOURCES_ONLY: 'RBAC_OWN_RESOURCES_ONLY',
  RBAC_OVERRIDE_NOT_FOUND: 'RBAC_OVERRIDE_NOT_FOUND',

  // Kiosk
  KIOSK_TOKEN_REQUIRED: 'KIOSK_TOKEN_REQUIRED',
  KIOSK_TOKEN_INVALID: 'KIOSK_TOKEN_INVALID',
  KIOSK_PATIENT_NOT_FOUND: 'KIOSK_PATIENT_NOT_FOUND',
  KIOSK_APPOINTMENT_NOT_FOUND: 'KIOSK_APPOINTMENT_NOT_FOUND',
  KIOSK_FORMS_UNAVAILABLE: 'KIOSK_FORMS_UNAVAILABLE',

  // Email
  EMAIL_LOG_NOT_FOUND: 'EMAIL_LOG_NOT_FOUND',
  EMAIL_CAN_ONLY_RESEND_FAILED: 'EMAIL_CAN_ONLY_RESEND_FAILED',
  EMAIL_TEMPLATE_NOT_FOUND: 'EMAIL_TEMPLATE_NOT_FOUND',
  EMAIL_CANNOT_DELETE_SYSTEM_TEMPLATE: 'EMAIL_CANNOT_DELETE_SYSTEM_TEMPLATE',

  SCHEDULE_OVERLAP: 'SCHEDULE_OVERLAP',
  SCHEDULE_INVALID_TIME_RANGE: 'SCHEDULE_INVALID_TIME_RANGE',
  SCHEDULE_PROVIDER_NOT_ACTIVE: 'SCHEDULE_PROVIDER_NOT_ACTIVE',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
