export type ClinicalNoteErrorCode =
  | 'CLINICAL_NOTE_REQUIRES_PROVIDER'
  | 'CLINICAL_NOTE_EDIT_LOCKED'
  | 'CLINICAL_NOTE_SIGNER_NOT_AUTHOR'
  | 'CLINICAL_NOTE_EMPTY'
  | 'CLINICAL_NOTE_PARENT_NOT_SIGNED'
  | 'CLINICAL_NOTE_PARENT_DELETED'
  | 'CLINICAL_NOTE_NOT_FOUND'
  | 'CLINICAL_NOTE_NOT_OWNER'
  | 'CLINICAL_NOTE_APPOINTMENT_PATIENT_MISMATCH';
